USE movies_new;
INSERT INTO directors (director_name)
Values 
('James Cameron'),
('Lee Unkrich'),
('Adrián Molina'),
('Christopher Nolan'),
('Morten Tyldum'),
('David Leitch'),
('Francis Ford Coppola'),
('Roman Polanski'),
('Roger Allers'),
('Rob Minkoff'),
('Jonathan Demme'),
('Edward Zwick'),
('Robert Zemeckis'),
('Ridley Scott'),
('Pete Docter'),
('James Cameron'),
('Lee Unkrich'),
('Adrián Molina'),
('Christopher Nolan'),
('Morten Tyldum'),
('David Leitch'),
('Francis Ford Coppola'),
('Roman Polanski'),
('Roger Allers'),
('Rob Minkoff'),
('Jonathan Demme'),
('Edward Zwick'),
('Robert Zemeckis'),
('Ridley Scott'),
('Pete Docter')
